package pl.polsl.meetandride.enums;

public enum ErrorCode {
    VALIDATION_FAILED, EMAIL_ALREADY_TAKEN,RESOURCE_NOT_FOUND,ILLEGAL_ARGUMENT_EXCEPTION,EMPTY_RESULT_DATA_ACCESS_EXCEPTION,NO_PERMISSIONS
}

